---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install docker-compose
  package:
    name: docker-compose
    state: latest

- name: Install Docker Module for Python
  pip:
    name: docker

# Create certificates for tls access from jenkins
- name: Expose docker api
  lineinfile:
    path: "/lib/systemd/system/docker.service"
    regexp: '^ExecStart='
    line: ExecStart=/usr/bin/dockerd -H fd:// -H=tcp://0.0.0.0:2375 --tls=false --containerd=/run/containerd/containerd.sock
  notify: Restart docker daemon