- name: Create application directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  with_items:
    - "{{ docker_app_dir }}/app-jenkins"

- name: Create Image directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  with_items:
    - "{{ docker_app_dir }}/app-jenkins/images"
    - "{{ docker_app_dir }}/app-jenkins/images/jenkins"
    - "{{ docker_app_dir }}/app-jenkins/images/jenkins-worker"
    - "{{ docker_app_dir }}/app-jenkins/images/jenkins-worker/.ssh"

- name: Prepare jenkins image files
  template:
    src: "./jenkins/{{ item }}"
    dest: "{{ docker_app_dir }}/app-jenkins/images/jenkins/{{ item | regex_replace('.j2','') }}"
  with_items:
    - casc.yaml.j2
    - Dockerfile.j2
    - plugins.txt.j2

- name: Prepare jenkins worker image files
  template:
    src: "./jenkins-worker/{{ item }}"
    dest: "{{ docker_app_dir }}/app-jenkins/images/jenkins-worker/{{ item | regex_replace('.j2','') }}"
  with_items:
    - Dockerfile.j2

- name: Prepare jenkins worker image files
  template:
    src: "./jenkins-worker/{{ item }}"
    dest: "{{ docker_app_dir }}/app-jenkins/images/jenkins-worker/.ssh/{{ item | regex_replace('.j2','') }}"
  with_items:
    - authorized_keys.j2

- name: Create Jenkins Docker image
  community.docker.docker_image:
    name: jenkins:v1.0
    build:
      path: "{{ docker_app_dir }}/app-jenkins/images/jenkins"
    source: build
    state: present